# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-08-30 23:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('citations', '0002_remove_citation_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='CitationExtended',
            fields=[
                ('citation_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='citations.Citation')),
                ('author', models.CharField(max_length=200)),
                ('institution', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=200)),
                ('doi', models.CharField(max_length=200)),
                ('data', models.FileField(upload_to='media/')),
                ('comment', models.TextField()),
            ],
            bases=('citations.citation',),
        ),
        migrations.AddField(
            model_name='citation',
            name='created_at',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
