# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-08-31 17:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citations', '0003_auto_20180830_2303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citation',
            name='dap_url',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='citation',
            name='data_hash',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='citationextended',
            name='author',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AlterField(
            model_name='citationextended',
            name='comment',
            field=models.TextField(default=None),
        ),
        migrations.AlterField(
            model_name='citationextended',
            name='data',
            field=models.FileField(default=None, upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='citationextended',
            name='doi',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AlterField(
            model_name='citationextended',
            name='institution',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AlterField(
            model_name='citationextended',
            name='title',
            field=models.CharField(default=None, max_length=200),
        ),
    ]
