# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-08-31 20:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citations', '0004_auto_20180831_1739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citation',
            name='created_at',
            field=models.DateTimeField(blank=True),
        ),
    ]
