# Generated by Django 2.1.2 on 2019-01-09 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citations', '0005_auto_20180831_2010'),
    ]

    operations = [
        migrations.CreateModel(
            name='CitationMetaData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('citation_pk', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='DOI',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doi', models.CharField(default=None, max_length=200)),
                ('citation_id', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='citationextended',
            name='doi',
        ),
    ]
